name: CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install node modules
        run: npm install
      - name: run unit tests
        run: npm test
      - name: build project for production
        run: npm run build
      - name: sync non index.html files with s3 bucket
        run: aws s3 sync ./dist s3://pokemon.kieranallen.me --exclude index.html --cache-control "max-age=31536000"
      - name: sync index.html with s3 bucket
        run: aws s3 sync ./dist s3://pokemon.kieranallen.me --cache-control "no-cache"
